#!/usr/bin/sh

p=$2
q=$3
r=$4
s=$5

img_preview() {
		kitty +kitten icat --silent --stdin no --transfer-mode file --place "${p}x${q}@${r}x${s}" "$1" < /dev/null > /dev/tty
}

case "$1" in
    *.tar*) tar tf "$1";;
    *.zip) unzip -l "$1";;
    *.rar) unrar l "$1";;
    *.7z) 7z l "$1";;
		*.jpg|*.jpeg|*.png|*.bmp|*.webp|*.gif|*.xpm|*.tiff) 
				img_preview "$1"
				;;
    *) bat "$1";;
esac
return 127 # nonzero retcode required for lf previews to reload
